language: python
python:
- '3.8'
dist: focal
os: linux
addons:
  sonarcloud:
    organization: menosse
    token: "${SONAR_TOKEN}"
jobs:
  include:
  - stage: Build & Test
    name: Unit Test, Quality & Security
    install:
    - pip install flask flask-wtf coverage
    script:
    - coverage run test.py || travis_terminate 1;
    - coverage report app.py || travis_terminate 1;
    - coverage xml app.py || travis_terminate 1;
    - sonar-scanner || travis_terminate 1;
  - stage: Stage Deploy
    name: Heroku Deploy
    script: skip
    deploy:
      provider: heroku
      api_key: "$HEROKU_API_KEY"
      edge: true
      app: "$app"
      on:
        branch: main
  - stage: Stage Test
    name: GET URL Stage
    script:
      - curl https://multicloud-fernando.herokuapp.com/ | grep Pipeline || travis_terminate 1;
#   - stage: Production Deploy
#     name: Google Api Engine
#     script: skip
#     deploy:
#       provider: gae
#       # keyfile: "../lab-devops-cloud-e2c2da9aee66.json"
#       keyfile: "/lab-devops-cloud.json"
#       project: lab-cloud-devops-01
#       on:
#         branch: main
#   - stage: Production Test
#     name: Get URL
#       script:
#         - curl https://multicloud-gcp-app.uc.r.appspot.com/ | grep Hello || travis_terminate 1;

before_install:
- openssl aes-256-cbc -K $encrypted_590a0f215273_key -iv $encrypted_590a0f215273_iv
  -in lab-devops-cloud.json.enc -out ~\/lab-devops-cloud.json -d