name: Pipeline GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  cicd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7.9]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install app dependencies
        run: |
          pip install -r requirements.txt

      - name: Unit Test
        run: |
          python -m unittest -v test

      - name: Deploy to STG try
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "multicloud-fernando"
          heroku_email: "famcsn2@gmail.com"
      
      - name: Curl Test on STG
        run: | 
          curl https://multicloud-fernando.herokuapp.com/ | grep Pipeline

      - name: Deploy to Prod
        # uses: google-github-actions/deploy-appengine@v0.2.0
        uses: google-github-actions/deploy-appengine@main
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_KEY }}
          promote: false
          version: v1